<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers" Version="4.15.0" PrivateAssets="All" />
    <PackageReference Include="xunit.v3" Version="4.0.1" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../sample-game/Sample-Game.csproj" />
  </ItemGroup>
</Project>
