version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
          
  - package-ecosystem: "docker-compose"
    directories:
      - "/.devcontainer"
      - "/.devcontainer/compose"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      docker-compose-group:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/client/sample-game"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/client/sample-game.Tests"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10