<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>SampleGame</RootNamespace>

    <!-- Force totally deterministic C# compilation -->
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/</PathMap>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <!-- Bug tracking for beta testers -->
    <PackageReference Include="Backtrace" Version="2.1.11" />

    <!-- Discord RPC -->
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    
    <!-- Dependency Injection -->
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />

    <!-- Multiplayer -->
    <PackageReference Include="NakamaClient" Version="3.22.1" />

    <!-- Integration testing -->
    <PackageReference Include="Testcontainers" Version="4.15.0" PrivateAssets="All" />
  </ItemGroup>
</Project>
